language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CATKIN_LINT=true
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE="rvip.repos"
    - BUILDER=colcon
    - ADDITIONAL_DEBS="ros-melodic-ros-environment"

  matrix:
    - ROS_DISTRO="melodic" ROS_REPO=main
    - ROS_DISTRO="melodic" ROS_REPO=testing

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
