language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - BEFORE_INSTALL_TARGET_DEPENDENCIES='./install_opengr.sh'
    - CATKIN_LINT=true
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="melodic"

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
